name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    concurrency: ${{ matrix.platform }}-${{ github.ref }}
    strategy:
      matrix:
        node: [lts/*]
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: starter
          password: starter
          database: starterdb
          port: 5432
          postgres-version: "14"
          ssl: true
        id: postgres
  
      - run: psql ${{ steps.postgres.outputs.connection-uri }} -c "SELECT 1"
      - run: psql service=${{ steps.postgres.outputs.service-name }} -c "SELECT 1"
      - run: psql -c "SELECT 1"
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
