name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    concurrency: ${{ matrix.platform }}-${{ github.ref }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres

        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
        run: |
          createuser starter
          createdb --owner starter starterdb
          psql -c "ALTER USER starter WITH PASSWORD 'starter'"
          
          psql ${{ steps.postgres.outputs.connection-uri }} -c "SELECT 1"
          psql service=${{ steps.postgres.outputs.service-name }} -c "SELECT 1"
          psql -c "SELECT 1"
          
          echo "${{ steps.postgres.outputs.connection-uri }}"
